# Update these values for your environment
# Example URL: jdbc:mysql://localhost:3306/food_ordering?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

db.url=jdbc:mysql://localhost:3306/food_ordering?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=A\#Tawfik2001\#
